# Generated by Django 5.2.8 on 2026-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='product_code',
            field=models.CharField(max_length=10),
        ),
    ]
