# Generated by Django 5.2.8 on 2026-05-17 09:28

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='agent_state',
            field=models.JSONField(default=chats.models.default_state),
        ),
    ]
