# Generated by Django 6.0.5 on 2026-05-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAC',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('power_consum', models.FloatField(blank=True, null=True)),
                ('cool_cap', models.IntegerField(blank=True, null=True)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('hertz', models.IntegerField(blank=True, null=True)),
                ('in_width', models.IntegerField(blank=True, null=True)),
                ('in_height', models.IntegerField(blank=True, null=True)),
                ('in_depth', models.IntegerField(blank=True, null=True)),
                ('out_width', models.IntegerField(blank=True, null=True)),
                ('out_height', models.IntegerField(blank=True, null=True)),
                ('out_depth', models.IntegerField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('dehumid', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ProductAC',
            },
        ),
        migrations.CreateModel(
            name='ProductFridge',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('power_consum', models.FloatField(blank=True, null=True)),
                ('install_type', models.CharField(blank=True, max_length=100, null=True)),
                ('door_cnt', models.IntegerField(blank=True, null=True)),
                ('total_cap', models.IntegerField(blank=True, null=True)),
                ('refrige_cap', models.IntegerField(blank=True, null=True)),
                ('freeze_cap', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('door_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cool_type', models.CharField(blank=True, max_length=100, null=True)),
                ('smart_diag', models.IntegerField(blank=True, null=True)),
                ('ice_maker', models.IntegerField(blank=True, null=True)),
                ('manual_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ProductFridge',
            },
        ),
        migrations.CreateModel(
            name='ProductVAC',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('power_consum', models.IntegerField(blank=True, null=True)),
                ('unit_width', models.IntegerField(blank=True, null=True)),
                ('unit_height', models.IntegerField(blank=True, null=True)),
                ('unit_depth', models.IntegerField(blank=True, null=True)),
                ('tower_width', models.IntegerField(blank=True, null=True)),
                ('tower_height', models.IntegerField(blank=True, null=True)),
                ('tower_depth', models.IntegerField(blank=True, null=True)),
                ('unit_weight', models.FloatField(blank=True, null=True)),
                ('tower_weight', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('suction_power', models.IntegerField(blank=True, null=True)),
                ('battery_cnt', models.IntegerField(blank=True, null=True)),
                ('manual_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ProductVAC',
            },
        ),
        migrations.CreateModel(
            name='ProductWash',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('power_consum', models.IntegerField(blank=True, null=True)),
                ('washing_cap', models.IntegerField(blank=True, null=True)),
                ('drying_cap', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('door_design', models.CharField(blank=True, max_length=100, null=True)),
                ('control_type', models.CharField(blank=True, max_length=100, null=True)),
                ('door_type', models.CharField(blank=True, max_length=100, null=True)),
                ('water_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('spin_op', models.IntegerField(blank=True, null=True)),
                ('manual_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ProductWash',
            },
        ),
        migrations.CreateModel(
            name='ScreenResolution',
            fields=[
                ('resol_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ScreenResolution',
            },
        ),
        migrations.CreateModel(
            name='ProductTV',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('power_consum', models.FloatField(blank=True, null=True)),
                ('screen_size', models.IntegerField(blank=True, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_rate', models.IntegerField(blank=True, null=True)),
                ('os_type', models.CharField(blank=True, max_length=100, null=True)),
                ('speaker_output', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('manual_link', models.URLField(blank=True, max_length=500, null=True)),
                ('resol_code', models.ForeignKey(db_column='resol_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.screenresolution')),
            ],
            options={
                'db_table': 'ProductTV',
            },
        ),
    ]
